### ISSUE TITLE
[BUG] Close button showing on next line

### ISSUE THREAD

**Issue by garrettseward** [Suibs/Open-Tree-Style-Tab#11]
![image](https://user-images.githubusercontent.com/2507359/85081969-606f6780-b182-11ea-8a09-bf903f2b6f0a.png)

OS: Arch Linux
Browser: Chromium

**Comment by Suibs** [comment]
Hi @garrettseward, thank you for bringing this issue up. This is scheduled to be fixed in the upcoming update within the next few days.
